
giropopsSenhas:
  name: "giropops-senhas"
  image: "aguinho/giropops-senhas-pick:v1"
  replicas: 5
  labels:
    app: "giropops-senhas"
    env: "prod"
  service:
    type: "LoadBalancer"
    port: 5000
    targetPort: 5000
    name: "giropops-senhas-port"
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"

redis:
  image: "redis"
  replicas: 2
  labels:
    app: "redis"
    env: "prod"
  service:
    type: "ClusterIP"
    port: 6379
    targetPort: 6379
    name: "redis-port"
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1"
