
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: desabilitar-root-pod
spec:
  validationFailureAction: enforce
  rules:
  - name: check-run-as-root
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Não é possível rodar container como root"
      pattern:
        spec:
          containers:
          - securityContext:
              runAsNonRoot: true
