services: 
  giropops:
    build: .
    ports: 
      - "5000:5000"
    networks:
      - pick
    environment:
      REDIS_HOST: redis

  redis:
    image: redis
    networks:
      - pick

networks:
  pick:


